services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - WEBHOOK_HOST=0.0.0.0
      - WEBHOOK_PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=cs
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8080:8080"

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=cs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
